version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:16
    steps:
      - checkout
      - run:
          name: Install SonarScanner
          command: |
            sudo apt-get update
            sudo apt-get install -y unzip
            wget https://download.java.net/java/GA/jdk17/0d483333a00540d886896bac774ff48b/35/GPL/openjdk-17_linux-x64_bin.tar.gz && \
            sudo mkdir -p /usr/lib/jvm && \
            sudo tar -zxvf openjdk-17_linux-x64_bin.tar.gz -C /usr/lib/jvm && \
            sudo rm openjdk-17_linux-x64_bin.tar.gz
            export JAVA_HOME=/usr/lib/jvm/jdk-17
            export PATH=$PATH:$JAVA_HOME/bin
            java -version
      - run:
          name: Install Dependencies and Run Tests
          command: |
            npm install sonar-scanner -g
      - run:
          name: Run SonarQube Analysis
          command: npm run sonar-scanner
          environment:
            SONAR_TOKEN: sqp_91b1c005b2a54e05584b88f42cbdec058b81750f
            SONAR_HOST_URL: http://51.20.52.215:9000
