version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: npm install
      - run: npm test
      
  sonarqube-analysis:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run:
          name: SonarQube Analysis
          command: |
            curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.0/install.sh | bash
            nvm install node:16
            mkdir ~/.npm-global
            npm config set prefix '~/.npm-global'
            export PATH=~/.npm-global/bin:$PATH
            sudo npm install -g sonarqube-scanner
            sonar-scanner \
              -Dsonar.projectKey=NodeJs-Application \
              -Dsonar.sources=. \
              -Dsonar.host.url=http://51.20.52.215:9000 \
              -Dsonar.login=sqp_8277de1203f23677561066ecdf3e16c6e28ed0b6

workflows:
  version: 2
  build_and_analyze:
    jobs:
      - build
      - sonarqube-analysis:
          requires:
            - build
          filters:
            branches:
              only: main
