version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:16
    steps:
      - checkout
      - run:
          name: Install SonarScanner
          command: |
            sudo apt-get update
            sudo apt-get install -y unzip
      - run:
          name: Install Dependencies and Run Tests
          command: |
            npm install
            npm install sonar-scanner -g
      - run:
          name: Run SonarQube Analysis
          command: npm run sonar-scanner
          environment:
            SONAR_TOKEN: sqp_91b1c005b2a54e05584b88f42cbdec058b81750f
            SONAR_HOST_URL: http://51.20.52.215:9000
