version: 2.1
jobs:
  build:
    docker:
      - image: ubuntu:latest  
    steps:
      - checkout
      - run: apt-get update && apt-get install -y nodejs npm
      - run: npm install
  sonarqube-analysis:
    docker:
      - image: ubuntu:latest  
    steps:
      - checkout
      - run:
          name: Install Node.js and SonarQube Scanner
          command: |
            apt-get update && apt-get install -y nodejs npm && apt-get install -y wget
            wget https://download.java.net/java/GA/jdk17/0d483333a00540d886896bac774ff48b/35/GPL/openjdk-17_linux-x64_bin.tar.gz && \
            mkdir -p /usr/lib/jvm && \
            tar -zxvf openjdk-17_linux-x64_bin.tar.gz -C /usr/lib/jvm && \
            rm openjdk-17_linux-x64_bin.tar.gz
            export JAVA_HOME=/usr/lib/jvm/jdk-17
            export PATH=$PATH:$JAVA_HOME/bin
            java -version
            npm install -g sonarqube-scanner
      - run:
          name: SonarQube Analysis
          command: |
            sonar-scanner \
              -Dsonar.projectKey=NodeJs-Application \
              -Dsonar.host.url=http://51.20.52.215:9000 \
              -Dsonar.login=sqp_91b1c005b2a54e05584b88f42cbdec058b81750f

workflows:
  version: 2
  build_and_analyze:
    jobs:
      - build
      - sonarqube-analysis:
          requires:
            - build
          filters:
            branches:
              only: main
