version: 2.1
jobs:
  build:
    docker:
      - image: ubuntu:latest  
    steps:
      - checkout
      - run: apt-get update && apt-get install -y nodejs npm
      - run: npm install
  sonarqube-analysis:
    docker:
      - image: ubuntu:latest  
    steps:
      - checkout
      - run:
          name: Install Node.js and SonarQube Scanner
          command: |
            ## Installation of sonarqube scanner
            apt-get update && apt-get install -y wget && apt-get install -y curl
            curl -sL https://deb.nodesource.com/setup_16.x | bash -
            apt-get install -y nodejs
            node -v
            npm -v
            wget https://download.java.net/java/GA/jdk17/0d483333a00540d886896bac774ff48b/35/GPL/openjdk-17_linux-x64_bin.tar.gz && \
            mkdir -p /usr/lib/jvm && \
            tar -zxvf openjdk-17_linux-x64_bin.tar.gz -C /usr/lib/jvm && \
            rm openjdk-17_linux-x64_bin.tar.gz
            export JAVA_HOME=/usr/lib/jvm/jdk-17
            export PATH=$PATH:$JAVA_HOME/bin
            java -version
            export LANG=C.UTF-8 LC_ALL=C.UTF-8
            npm install -g sonarqube-scanner
      - run:
          name: SonarQube Analysis
          command: |
            sonar-scanner \
              -Dsonar.projectKey=Innobit-Test \
              -Dsonar.sources=. \
              -Dsonar.host.url=http://sonar.innobitsystems.com \
              -Dsonar.login=sqp_333c5f4588b5fb31e3f79392b7f11d7ec8f410d2      
workflows:
  version: 2
  build_and_analyze:
    jobs:
      - build
      - sonarqube-analysis:
          requires:
            - build
          filters:
            branches:
              only: main
